name: bibtex-tidy
description: GitHub Action to run bibtex-tidy, a BibTeX formatter
author: Gray Espinoza

branding:
  icon: align-left
  color: black

inputs:
  opts:
    description: CLI options to pass to bibtex-tidy
    required: false
  inputs:
    description: input files/directories to pass to bibtex-tidy
    required: false
    default: .

runs:
  using: "docker"
  image: "Dockerfile"
