name: bibtex-tidy
description: GitHub Action to run bibtex-tidy, a BibTeX formatter
author: Gray Espinoza

branding:
  icon: align-left
  color: black

inputs:
  args:
    description: CLI arguments to pass to bibtex-tidy
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
